overwrite: true
schema: "https://graphql.anilist.co"
documents:
  - "web/src/**/*.graphql"
generates:
  web/src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
config:
  fetcher:
    func: "../network/createFetcher#createFetcher"
  maybeValue: T | undefined
  skipTypename: true
