overwrite: true
schema: "https://graphql.anilist.co"
documents:
  - "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
config:
  fetcher:
    endpoint: "'/anilist'"
  maybeValue: T | undefined
  skipTypename: true
